# Generated by Django 4.1.7 on 2023-02-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('origin', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
            ],
        ),
    ]
